import type {Metadata} from "next";
import "../../globals.css";
import {ThemeProvider} from "@/components/theme-provider"
import {ModeToggle} from "@/components/mode";
import React from "react";
import LocalSwitcher from "@/components/local-switcher";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>
            <main>
            <div className="flex justify-end">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="fixed flex flex-1">
                        <LocalSwitcher/>
                        <ModeToggle/>
                    </div>
                </ThemeProvider>
            </div>
            {children}
            </main>
        </>
    );
}
